project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"


website:
  open-graph: true
  title: "Ashley Fehr"
  site-url: https://amafehr.github.io
  repo-url: https://github.com/amafehr/amafehr.github.io
  favicon: images/octopus_icon_transparent.png

  navbar:
    style: "floating"
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right:
      - href: https://github.com/amafehr/amafehr.github.io
        icon: github
        aria-label: "Source Code"
      - icon: stars
        href: "#"
        id: "stars-btn"
        aria-label: "Confetti"
    search: true
    pinned: true

format:
  html:
    theme: _custom.scss
    toc: false
    smooth-scroll: true
    html-math-method: katex
    include-in-header:
      - includes.html
    footnotes-hover: false
    code-fold: true
    grid:
      body-width: 1100px
    include-after-body:
      - text: "<script src='/scripts/stars.js'></script>"
