### Fictional archetypes in straight-queer space
Using the
[Archetypometrics dataset](https://compstorylab.org/archetypometrics/),
we analyze samples of characters in
stories across TV, film, and literature, focusing on the trait differential spanning
straight to queer.
[Results](https://arxiv.org/abs/2607.08859)
show a multitude of archetypes among queer characters and their nearest neighbors,
demonstrating a paradoxical breadth of representation
while surfacing persist societal biases.


### Principles of complex systems helpers
[This repository](https://github.com/amafehr/pocs_helpers) (in development)
codes helpers for the purpose of making principled complexity methods
quickly accessible for learning or applying. Examples include working with text,
understanding your data, running a linear regression, or calculating and visualizing
rank of types in a system.


### Statistical laws in conversations
We analyzed linguistic scaling in conversational texts (naturalistic video
and fictional).
[Results](https://arxiv.org/abs/2512.18072)
demonstrate Zipf's and Heaps' laws
in different conversational mediums with differences by parts of speech.

### py-allotax
We implemented a python wrapper and interface around javascript implementation to
compare 2 systems' rankings of types with the goal of accessibility for researchers.
The
[Python py-allotax](https://github.com/compstorylab/py-allotax)
(published on PyPi) allows users to make allotaxonometric
comparisons and plots programmatically. We describe the
allotaxonometric tool ecosystem in
[our paper](https://arxiv.org/abs/2506.21808).


### Reddit as network data
I explored modeling
[Reddit posts as conversations and network data](https://github.com/amafehr/stat-6990-reddit-network).
I found that positive replies yields further discussion.
Further, higher user activity can contribute to
their rank rather than needing to be an influential user with high comment
scores across Reddit.


### Linguistic coordination
I assessed the representativeness of
the CANDOR dataset to the U.S. population and analyzed the
linguistic coordination of conversations
in CANDOR---how much speakers tailor their linguistic style in responses to the speaker,
confirming this effect in stranger conversations.